version: '3'

services:
  fastapi:
    build: fastapi
    environment:
      UVICORN_HOST: ${UVICORN_HOST}
      UVICORN_PORT: ${UVICORN_PORT}
    expose:
    - ${UVICORN_PORT}
    ports:
    - ${UVICORN_PORT}:${UVICORN_PORT}
    restart: always
